<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<meta http-equiv="x-ua-compatible" content="IE=edge"/>
<title>Test results - UserServiceTest</title>
<link href="../css/base-style.css" rel="stylesheet" type="text/css"/>
<link href="../css/style.css" rel="stylesheet" type="text/css"/>
<script src="../js/report.js" type="text/javascript"></script>
</head>
<body>
<div id="content">
<h1>UserServiceTest</h1>
<div class="breadcrumbs">
<a href="../index.html">all</a> &gt; 
<a href="../packages/skcc.arch.biz.small.user.service.html">skcc.arch.biz.small.user.service</a> &gt; UserServiceTest</div>
<div id="summary">
<table>
<tr>
<td>
<div class="summaryGroup">
<table>
<tr>
<td>
<div class="infoBox" id="tests">
<div class="counter">8</div>
<p>tests</p>
</div>
</td>
<td>
<div class="infoBox" id="failures">
<div class="counter">3</div>
<p>failures</p>
</div>
</td>
<td>
<div class="infoBox" id="ignored">
<div class="counter">0</div>
<p>ignored</p>
</div>
</td>
<td>
<div class="infoBox" id="duration">
<div class="counter">0.038s</div>
<p>duration</p>
</div>
</td>
</tr>
</table>
</div>
</td>
<td>
<div class="infoBox failures" id="successRate">
<div class="percent">62%</div>
<p>successful</p>
</div>
</td>
</tr>
</table>
</div>
<div id="tabs">
<ul class="tabLinks">
<li>
<a href="#tab0">Failed tests</a>
</li>
<li>
<a href="#tab1">Tests</a>
</li>
<li>
<a href="#tab2">Standard output</a>
</li>
</ul>
<div id="tab0" class="tab">
<h2>Failed tests</h2>
<div class="test">
<a name="이미존재하는_사용자_생성시_에러발생()"></a>
<h3 class="failures">이미존재하는_사용자_생성시_에러발생()</h3>
<span class="code">
<pre>org.opentest4j.AssertionFailedError: Unexpected exception type thrown, expected: &lt;java.lang.IllegalStateException&gt; but was: &lt;skcc.arch.app.exception.CustomException&gt;
	at app//org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at app//org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:67)
	at app//org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:35)
	at app//org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:3128)
	at app//skcc.arch.biz.small.user.service.UserServiceTest.이미존재하는_사용자_생성시_에러발생(UserServiceTest.java:80)
	at java.base@21.0.4/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base@21.0.4/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base@21.0.4/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: skcc.arch.app.exception.CustomException: 이미 존재하는 요소입니다.
	at app//skcc.arch.biz.user.service.UserService.checkUserExistByEmail(UserService.java:130)
	at app//skcc.arch.biz.user.service.UserService.signUp(UserService.java:46)
	at app//skcc.arch.biz.small.user.service.UserServiceTest.lambda$이미존재하는_사용자_생성시_에러발생$0(UserServiceTest.java:80)
	at app//org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:53)
	... 6 more
</pre>
</span>
</div>
<div class="test">
<a name="잘못된_정보로_로그인_시도()"></a>
<h3 class="failures">잘못된_정보로_로그인_시도()</h3>
<span class="code">
<pre>org.opentest4j.AssertionFailedError: Unexpected exception type thrown, expected: &lt;java.lang.IllegalStateException&gt; but was: &lt;skcc.arch.app.exception.CustomException&gt;
	at app//org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at app//org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:67)
	at app//org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:35)
	at app//org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:3128)
	at app//skcc.arch.biz.small.user.service.UserServiceTest.잘못된_정보로_로그인_시도(UserServiceTest.java:105)
	at java.base@21.0.4/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base@21.0.4/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base@21.0.4/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: skcc.arch.app.exception.CustomException: 비밀번호가 일치하지 않습니다.
	at app//skcc.arch.biz.user.service.UserService.authenticate(UserService.java:62)
	at app//skcc.arch.biz.small.user.service.UserServiceTest.lambda$잘못된_정보로_로그인_시도$1(UserServiceTest.java:105)
	at app//org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:53)
	... 6 more
</pre>
</span>
</div>
<div class="test">
<a name="존재하지_않은_이메일로_로그인_시도()"></a>
<h3 class="failures">존재하지_않은_이메일로_로그인_시도()</h3>
<span class="code">
<pre>org.opentest4j.AssertionFailedError: Unexpected exception type thrown, expected: &lt;java.lang.IllegalStateException&gt; but was: &lt;skcc.arch.app.exception.CustomException&gt;
	at app//org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at app//org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:67)
	at app//org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:35)
	at app//org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:3128)
	at app//skcc.arch.biz.small.user.service.UserServiceTest.존재하지_않은_이메일로_로그인_시도(UserServiceTest.java:117)
	at java.base@21.0.4/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base@21.0.4/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base@21.0.4/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: skcc.arch.app.exception.CustomException: 요소가 존재하지 않습니다.
	at app//skcc.arch.biz.user.service.UserService.lambda$authenticate$1(UserService.java:59)
	at java.base@21.0.4/java.util.Optional.orElseThrow(Optional.java:403)
	at app//skcc.arch.biz.user.service.UserService.authenticate(UserService.java:59)
	at app//skcc.arch.biz.small.user.service.UserServiceTest.lambda$존재하지_않은_이메일로_로그인_시도$2(UserServiceTest.java:117)
	at app//org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:53)
	... 6 more
</pre>
</span>
</div>
</div>
<div id="tab1" class="tab">
<h2>Tests</h2>
<table>
<thead>
<tr>
<th>Test</th>
<th>Duration</th>
<th>Result</th>
</tr>
</thead>
<tr>
<td class="success">ID로_사용자_조회()</td>
<td class="success">0.001s</td>
<td class="success">passed</td>
</tr>
<tr>
<td class="success">userCreate_를_이용해_생성한다()</td>
<td class="success">0s</td>
<td class="success">passed</td>
</tr>
<tr>
<td class="failures">이미존재하는_사용자_생성시_에러발생()</td>
<td class="failures">0.002s</td>
<td class="failures">failed</td>
</tr>
<tr>
<td class="failures">잘못된_정보로_로그인_시도()</td>
<td class="failures">0.002s</td>
<td class="failures">failed</td>
</tr>
<tr>
<td class="success">전체_사용자_조회()</td>
<td class="success">0s</td>
<td class="success">passed</td>
</tr>
<tr>
<td class="success">정상적인_계정으로_토큰생성_검증()</td>
<td class="success">0.032s</td>
<td class="success">passed</td>
</tr>
<tr>
<td class="failures">존재하지_않은_이메일로_로그인_시도()</td>
<td class="failures">0.001s</td>
<td class="failures">failed</td>
</tr>
<tr>
<td class="success">페이지정보를_이용한_사용자_조회()</td>
<td class="success">0s</td>
<td class="success">passed</td>
</tr>
</table>
</div>
<div id="tab2" class="tab">
<h2>Standard output</h2>
<span class="code">
<pre>2025-07-08T13:43:27.683+09:00  INFO 24308 --- [    Test worker] skcc.arch.biz.user.service.UserService   : generated token : eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0MUBzay5jb20iLCJ1aWQiOiJ0ZXN0MUBzay5jb20iLCJyb2xlIjpbXSwiZW1haWwiOiJ0ZXN0MUBzay5jb20iLCJ1c2VybmFtZSI6Iu2Zjeq4uOuPmTEiLCJpYXQiOjE3NTE5NDk4MDcsImV4cCI6MTc1MTk1MTYwN30.stB4Iwqt5_RGcqniAOAdudHeStxCMqwf97fc6AlECCs
</pre>
</span>
</div>
</div>
<div id="footer">
<p>
<div>
<label class="hidden" id="label-for-line-wrapping-toggle" for="line-wrapping-toggle">Wrap lines
<input id="line-wrapping-toggle" type="checkbox" autocomplete="off"/>
</label>
</div>Generated by 
<a href="http://www.gradle.org">Gradle 8.11.1</a> at 2025. 7. 8. 오후 1:43:30</p>
</div>
</div>
</body>
</html>
